dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    pip: true
    directories:
        - $HOME/download/
        - $HOME/miniconda3_$TRAVIS_OS_NAME

matrix:
    include:
      - os: linux
        dist: trusty
        sudo: required
        addons:
          apt-packages:
            - build-essential
            - git
            - curl

before_install:
  - bash .travis/travis_before_install.sh

install:
  - export PATH="/home/travis/miniconda3/bin:$PATH"
  - bash .travis/travis_install.sh
  - conda install --yes -c bioconda snakemake

script:
  - echo $PATH
  - python --version

  - export PATH="$HOME"/miniconda3_$TRAVIS_OS_NAME:$PATH"
  - source activate smsk_khmer_trinity
  - snakemake --use-conda --jobs 2

after_faillure:
  - find results -name "*.log" -exec tail -vn +0 {} \; -exec echo -e "" \;
