dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/download/
        #- $HOME/miniconda3/

before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="/home/travis/miniconda3/bin:$PATH"

install:
  - bash src/install/conda_env.sh

script:
  - source activate smsk_khmer_trinity
  - snakemake -j2 results/assembly/Trinity.fasta

after_error:
    - cat results/diginorm/load_into_counting.log
