dist: trusty

language: bash

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential curl git
  - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b
  - export PATH="/home/travis/miniconda3/bin:$PATH"

jobs:
    include:
        - stage: conda_env
          script:
            - bash src/install/conda_env.sh
        - stage: preprocessing
          script:
            - source activate smsk_khmer_trinity
            - snakemake results/assembly/{left,right}.fq -j
        - stage: assembly
          script:
            - source activate smsk_khmer_trinity
            - snakemake -j

