dist: trusty

language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/download/
        #- $HOME/miniconda3/

before_install:
  - bash .travis/travis_before_install.sh
  - export PATH="/home/travis/miniconda3/bin:$PATH"

install:
  - bash src/install/conda_env.sh

script:
  - source activate smsk_khmer_trinity
<<<<<<< HEAD
  - mkdir -p results/assembly/ && touch results/assembly/run_trinity.log
  - (tail --follow --sleep-interval 60 results/assembly/run_trinity.log & ) && travis_wait snakemake -j 2 && kill %1
=======
  - snakemake -j1 results/assembly/Trinity.fasta

after_failure:
    - cat results/assembly/merge_right_and_left.log
>>>>>>> travis
