prefix:
    test # Prefix for the assembly. This should an animal, plant, cell line, ...

samples_pe:
    pe1:
        forward: data/fastq_raw/test1_1.fastq.gz
        reverse: data/fastq_raw/test1_2.fastq.gz
        adaptor: ./data/adapters/TruSeq3-PE-2.fa
        phred:   phred33
#    pe2:
#        forward: data/fastq_raw/test2_1.fastq.gz
#        reverse: data/fastq_raw/test2_2.fastq.gz
#        adaptor: ./src/adapters/TruSeq3-PE-2.fa
#        phred:   phred33

samples_se:
    se3:
        single:   data/fastq_raw/test3.fastq.gz
        adaptor:  ./data/adapters/TruSeq3-PE-2.fa
        phred:    phred33


trimmomatic_params:
    "LEADING:20 TRAILING:20 AVGQUAL:30 MINLEN:32 TOPHRED33"


# Consider this if you change the values:
# http://khmer.readthedocs.org/en/v1.0/choosing-table-sizes.html
diginorm_params:
    ksize: "32" # Remember to set MINLEN in trimmomatic_params at least this value!
    cutoff: "20"
    n_tables: "4"   # n_tables * max_table_size must be < your RAM in bytes
    max_table_size: "1e9" # 4 tables * 1e9 (~1GB) ~ 4Gb - Raise it to 4e9 for nontesting purposes

trinity_params:
    memory: "2G"
