# Running parameters of the pipeline
---
trimmomatic:
    extra: "LEADING:20 TRAILING:20 AVGQUAL:30 MINLEN:32 TOPHRED33"


# Consider this if you change the values:
# http://khmer.readthedocs.org/en/v1.0/choosing-table-sizes.html
# Remember to set MINLEN in trimmomatic_params at least the value of ksize
# max_table_size: 4 tables * 1e9 (~1GB) ~ 4Gb - Raise it to 4e9 for
# nontesting purposes
diginorm:
    ksize: "32"
    cutoff: "20"
    n_tables: "4"  # n_tables * max_table_size must be < your RAM in bytes
    max_table_size: "1e8"


trinity:
    memory: "2G"
