# Travis's execution file
---
language: bash

addons:
    apt_packages:
        - build-essential
        - git
        - curl
        - shellcheck

cache:
    directories:
        - $HOME/miniconda/

install:
    - bash .travis/install.sh

script:
    - export PATH="$HOME/miniconda/bin:$PATH"
    - echo $PATH
    - ./pre-commit
